condense_wildcard_suffixes = true
float_literal_trailing_zero = "Always"
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "One"
hex_literal_case = "Upper"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
style_edition = "2027"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
