[unstable]
build-std = [
    "core",
    "alloc",
    "compiler_builtins"
]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true

[build]
# TODO: switch to build-std: https://rust-lang.github.io/rfcs/3874-build-std-always.html
# build-std = { when = "always", crates = "alloc" }
target = "arch/x86/target.json"
