name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: cargo fmt
        run: |
          cargo fmt --check

  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: cargo fix
        run: |
          cargo fix --all-features
          git diff --exit-code
      - name: cargo fix edition
        run: |
          cargo fix --edition --all-features
          git diff --exit-code

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: cargo clippy
        run: |
          cargo clippy --all-features
      - name: cargo clippy --release
        run: |
          cargo clippy --release --all-features

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          - debug
          - release
        bootprotocol:
          - multiboot
          - multiboot2
    container: ghcr.io/alisterd51/cross-toolchain:nightly
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Build ${{ matrix.build }}, ${{ matrix.bootprotocol }}
        run: |
          make all BUILD=${{ matrix.build }} BOOTPROTOCOL=${{ matrix.bootprotocol }}
