name: Nightly Release

on:
  workflow_dispatch:
  schedule:
    - cron: '42 0 * * *'

jobs:
  nightly-prerelease:
    permissions: write-all
    runs-on: ubuntu-latest
    container: ghcr.io/alisterd51/cross-toolchain:nightly
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Build ISO
        run: |
          make iso BUILD=release
      - name: Create nightly tag
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/nightly',
              sha: context.sha
            }).catch(err => {
              if (err.status !== 422) throw err;
              github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/nightly',
                sha: context.sha
              });
            })
      - name: Release
        uses: softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8 # v2
        with:
          files: |
            build/release/gratos.x86.iso
          prerelease: true
          name: nightly
          tag_name: nightly
