name: Nightly Release

on:
  schedule:
    - cron: '42 0 * * *'

jobs:
  nightly-prerelease:
    runs-on: ubuntu-latest
    container: ghcr.io/alisterd51/cross-toolchain:nightly
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Build ISO
        run: |
          make iso BUILD=release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/release/kernel.x86.iso
          prerelease: true
          name: "nightly"
