name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    container: ghcr.io/alisterd51/cross-toolchain:nightly
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Build ISO
        run: |
          make iso BUILD=release BOOTPROTOCOL=multiboot2 BOOTLOADER=grub
          make iso BUILD=release BOOTPROTOCOL=multiboot2 BOOTLOADER=limine
      - name: Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3
        with:
          files: |
            build/release/gratos.x86.grub.iso
            build/release/gratos.x86.limine.iso
