name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    container: ghcr.io/alisterd51/cross-toolchain:nightly
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Build ISO
        run: |
          make iso BUILD=release BOOTLOADER=grub
          make iso BUILD=release BOOTLOADER=limine
      - name: Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        with:
          files: |
            build/release/gratos.x86.grub.iso
            build/release/gratos.x86.limine.iso
