name: Renovate config validator

on:
  pull_request:
    paths:
      - 'renovate.json'

jobs:
  lint-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Use Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: '24.x'
      - name: run renovate-config-validator
        run: |
          jq . renovate.json
          npx --yes --package renovate@latest -- renovate-config-validator --strict
