name: Renovate config validator

on:
  pull_request:
    paths:
      - 'renovate.json'

jobs:
  lint-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24.x'
      - name: run renovate-config-validator
        run: |
          jq . renovate.json
          npx --yes --package renovate@latest -- renovate-config-validator --strict
